FROM archlinux:latest
# pacman's seccomp sandbox does not work under qemu emulation (arm64 hosts)
RUN sed -i 's/^#\?DisableSandbox.*/DisableSandbox/' /etc/pacman.conf; grep -q '^DisableSandbox' /etc/pacman.conf || sed -i 's/^\[options\]/[options]\nDisableSandbox/' /etc/pacman.conf
RUN pacman -Syu --noconfirm --needed rust python bash gcc && pacman -Scc --noconfirm
WORKDIR /work
