# bash-tools @VERSION@ -- syntax highlighting and live completion for bash.
# Generated by `bash-tools init`; source it from ~/.bashrc (last is best).
[[ $- == *i* ]] || return 0 2>/dev/null
(( BASH_VERSINFO[0] >= 5 )) || return 0
[[ -z ${__bt_r-} && -t 0 && -t 2 ]] || return 0
[[ -o posix ]] && return 0

__bt_bin=@BIN@
[[ -x $__bt_bin ]] || return 0
__bt_rows=${BASH_TOOLS_LIST_ROWS:-8}
__bt_w= __bt_pid= __bt_busy= __bt_ack= __bt_last_refresh=0 __bt_user_winch= __bt_n=0 __bt_nl=

# PS0 is expanded once per executed command line, right before it runs: erase
# the completion list below the prompt and bump a counter that tells the
# daemon which prompt a message belongs to (no DEBUG trap needed).
__bt_x=()
PS0="${PS0-}"'\e[J${__bt_x[__bt_n++]-}'

# Start the daemon now (a fork only); the handshake happens at the first prompt.
exec {__bt_r}< <("$__bt_bin" daemon)

# One `bind -f` is ~30x cheaper than individual `bind` calls; only the hooks
# need `bind -x`. Only the active editing mode is set up.
bind -f @INPUTRC@
if [[ -o vi ]]; then
    __bt_km=vi-insert
    bind -m vi-command -x '"\e[9999;2~": __bt_ehook'
    bind -m vi-command -x '"\e[9999;6~": __bt_accept'
else
    __bt_km=emacs
fi
bind -m "$__bt_km" -x '"\e[9999;1~": __bt_hook'
bind -m "$__bt_km" -x '"\e[9999;2~": __bt_ehook'
bind -m "$__bt_km" -x '"\e[9999;6~": __bt_accept'
bind -m "$__bt_km" -x '"\C-i": __bt_tab'
bind -m "$__bt_km" -x '"\e[Z": __bt_stab'
unset __bt_km

__bt_hook() { [[ -z $__bt_w ]] || printf 'l\0%s\0%s\0%s\0' "$READLINE_LINE" "$READLINE_POINT" "$__bt_n" >&"$__bt_w" || :; }
__bt_ehook() { [[ -z $__bt_w ]] || printf 'e\0%s\0%s\0%s\0' "$READLINE_LINE" "$READLINE_POINT" "$__bt_n" >&"$__bt_w" || :; }
__bt_accept() { [[ -z $__bt_w ]] || printf 'a\0%s\0' "$__bt_n" >&"$__bt_w" || :; }
__bt_tab() { __bt_menu t; }
__bt_stab() { __bt_menu T; }
__bt_menu() {
    [[ -n $__bt_w ]] || return 0
    local reply
    __bt_busy=1
    printf '%s\0%s\0%s\0%s\0' "$1" "$READLINE_LINE" "$READLINE_POINT" "$__bt_n" >&"$__bt_w"
    while IFS= read -r -d '' -u "$__bt_r" -t 5 reply; do
        case $reply in
        I)  IFS= read -r -d '' -u "$__bt_r" -t 5 READLINE_LINE
            IFS= read -r -d '' -u "$__bt_r" -t 5 READLINE_POINT
            break ;;
        C)  # the daemon wants the compspec of a command
            IFS= read -r -d '' -u "$__bt_r" -t 5 reply
            { printf 'S\0'; complete -p -- "$reply" 2>/dev/null || complete -p -D 2>/dev/null || :; printf '\0'; } >&"$__bt_w" ;;
        R)  __bt_compspec ;;
        *)  break ;;
        esac
    done
    __bt_busy=
    printf 'd\0' >&"$__bt_w"
}

# Run one part of a compspec for the daemon (bash's programmable completion
# only runs from readline's own Tab). Results go back newline-separated.
__bt_compspec() {
    local kind arg cmd n i w st=0
    local COMP_LINE COMP_POINT COMP_CWORD COMP_TYPE=9 COMP_KEY=9 COMPREPLY=() __bt_compopts=
    local -a COMP_WORDS=()
    IFS= read -r -d '' -u "$__bt_r" -t 5 kind
    IFS= read -r -d '' -u "$__bt_r" -t 5 arg
    IFS= read -r -d '' -u "$__bt_r" -t 5 cmd
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_CWORD
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_LINE
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_POINT
    IFS= read -r -d '' -u "$__bt_r" -t 5 n
    for ((i = 0; i < n; i++)); do
        IFS= read -r -d '' -u "$__bt_r" -t 5 w
        COMP_WORDS+=("$w")
    done
    local cur=${COMP_WORDS[COMP_CWORD]-} prev=
    (( COMP_CWORD > 0 )) && prev=${COMP_WORDS[COMP_CWORD-1]}
    case $kind in
    F)  # `compopt` only works inside readline's completion; shim it so that
        # completion functions can still tell us about nospace/filenames.
        compopt() {
            while (( $# )); do
                case $1 in
                -o) __bt_compopts+=" $2"; shift ;;
                +o) __bt_compopts=${__bt_compopts// $2/}; shift ;;
                esac
                shift
            done
            return 0
        }
        if "$arg" "$cmd" "$cur" "$prev" 2>/dev/null; then st=0; else st=$?; fi
        unset -f compopt
        { printf 'Q\0%s\0%s\0' "$st" "$__bt_compopts"; (( ${#COMPREPLY[@]} )) && printf '%s\n' "${COMPREPLY[@]}"; printf '\0'; } >&"$__bt_w" ;;
    W)  { printf 'Q\0%s\0%s\0' 0 ''; compgen -W "$arg" -- "$cur" 2>/dev/null || :; printf '\0'; } >&"$__bt_w" ;;
    A)  { printf 'Q\0%s\0%s\0' 0 ''; compgen -A "$arg" -- "$cur" 2>/dev/null || :; printf '\0'; } >&"$__bt_w" ;;
    G)  { printf 'Q\0%s\0%s\0' 0 ''; compgen -G "$arg" 2>/dev/null || :; printf '\0'; } >&"$__bt_w" ;;
    C)  { printf 'Q\0%s\0%s\0' 0 ''; eval "$arg" '"$cmd" "$cur" "$prev"' 2>/dev/null || :; printf '\0'; } >&"$__bt_w" ;;
    *)  printf 'Q\0%s\0%s\0\0' 1 '' >&"$__bt_w" ;;
    esac
    return 0
}

# The daemon sends SIGWINCH when it has something to paint. Readline handles
# the signal (redrawing the line) before this trap runs, so our paint stays.
__bt_winch() {
    if [[ -n $__bt_busy ]]; then
        printf 'r\0' >&"$__bt_w" || :
    elif [[ -n $__bt_w ]]; then
        printf 'g\0%s\0' "$__bt_n" >&"$__bt_w" || :
        read -r -N 2 -u "$__bt_r" -t 2 __bt_ack || __bt_ack=
    fi
    # the user's own WINCH trap only for real resizes, not for our paints
    [[ -n $__bt_user_winch && $__bt_ack != ?m ]] && eval "$__bt_user_winch"
    return 0
}

# Erase the completion list before a command's output starts. Runs from the
# DEBUG trap, so it must skip our own hooks and always return 0 (with
# `extdebug` a non-zero status would skip the command).
__bt_connect() {
    local path pid
    read -r -u "$__bt_r" -t 5 path pid || return 1
    exec {__bt_w}<>"$path" || return 1
    __bt_pid=$pid
    printf 'i\0%s\0%s\0%s\0%s\0%s\0%s\0' "$$" "$HOME" "${HISTFILE-}" "${BASH_TOOLS_STYLES-}" \
        "$__bt_rows" "${BASH_TOOLS_OPTS-}" >&"$__bt_w"
    { printf 'V\0'; bind -v; printf '\0'; } >&"$__bt_w"
    __bt_refresh
    # Chain an existing WINCH trap: capturing `trap -p` output in the shell
    # costs a fork (or 0.3 ms in 5.3), so let the daemon parse it instead.
    { printf 'W\0'; trap -p WINCH; printf '\0'; } >&"$__bt_w"
    IFS= read -r -d '' -u "$__bt_r" -t 5 __bt_user_winch || __bt_user_winch=
    trap '__bt_winch' WINCH
    return 0
}
__bt_refresh() {
    { printf 'A\0'; compgen -A alias || :; printf '\0F\0'; compgen -A function || :; printf '\0'; } >&"$__bt_w"
}
__bt_disable() {
    [[ -n $__bt_w ]] && printf 'x\0' >&"$__bt_w"
    __bt_w=
    bind '"\C-i": complete'
    bind '"\e[Z": menu-complete-backward'
}
bash_tools_off() { __bt_disable; }

__bt_prompt() {
    if [[ -z $__bt_w ]]; then
        __bt_connect || return 0
    elif ! kill -0 "$__bt_pid" 2>/dev/null; then
        __bt_disable
        return 0
    fi
    local ps1=${PS1@P} ps2=${PS2@P} nl n
    # reserve rows below the prompt for the list (+ the prompt's own lines)
    nl=${ps1//[!$'\n']/}
    n=$(( __bt_rows + ${#nl} ))
    (( LINES > 0 && n > LINES / 2 )) && n=$(( LINES / 2 ))
    if (( n != ${#__bt_nl} )); then
        printf -v __bt_nl '%*s' "$n" ''
        __bt_nl=${__bt_nl// /$'\n'}
    fi
    if (( n > 0 )); then
        printf '\e[J%s\e[%dA' "$__bt_nl" "$n" >&2
    else
        printf '\e[J' >&2
    fi
    printf 'p\0%s\0%s\0%s\0%s\0%s\0%s\0%s\0' "$ps1" "$ps2" "$PWD" "$PATH" "$n" "$__bt_n" "${COMP_WORDBREAKS-}" >&"$__bt_w"
    if (( HISTCMD > 1 )); then
        { printf 'H\0'; fc -ln -1 2>/dev/null || :; printf '\0'; } >&"$__bt_w"
    fi
    if (( EPOCHSECONDS - __bt_last_refresh >= 5 )); then
        __bt_last_refresh=$EPOCHSECONDS
        __bt_refresh
    fi
    return 0
}

# Hook into PROMPT_COMMAND (string or array). The WINCH trap is installed at
# the first prompt, once the daemon is connected.
if [[ -n ${PROMPT_COMMAND+x} && ${PROMPT_COMMAND@a} == *a* ]]; then
    PROMPT_COMMAND+=(__bt_prompt)
else
    PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}__bt_prompt"
fi
