# bash-tools @VERSION@ -- syntax highlighting and live completion for bash.
# Generated by `bash-tools init`; source this from ~/.bashrc (last is best).
[[ $- == *i* ]] || return 0 2>/dev/null
(( BASH_VERSINFO[0] >= 5 )) || return 0
[[ -n ${__bt_r-} ]] && return 0
[[ -t 0 && -t 2 ]] || return 0

__bt_bin=@BIN@
__bt_rows=${BASH_TOOLS_LIST_ROWS:-8}
__bt_w= __bt_pid= __bt_busy= __bt_below= __bt_ack= __bt_last_refresh=0 __bt_user_winch=
printf -v __bt_nl '%*s' "$__bt_rows" ''
__bt_nl=${__bt_nl// /$'\n'}

# Start the daemon right away (a fork only); the handshake is deferred to the
# first prompt so it never delays the shell start.
exec {__bt_r}< <("$__bt_bin" daemon)

# Key bindings: one file read (`bind -f`) is ~30x cheaper than individual
# `bind` calls. The hooks themselves must be `bind -x`.
bind -f @INPUTRC@
for __bt_km in emacs vi-insert; do
    bind -m "$__bt_km" -x '"\e[9999;1~": __bt_hook'
    bind -m "$__bt_km" -x '"\e[9999;2~": __bt_ehook'
    bind -m "$__bt_km" -x '"\e[9999;6~": __bt_accept'
    bind -m "$__bt_km" -x '"\C-i": __bt_tab'
    bind -m "$__bt_km" -x '"\e[Z": __bt_stab'
done
bind -m vi-command -x '"\e[9999;2~": __bt_ehook'
bind -m vi-command -x '"\e[9999;6~": __bt_accept'
unset __bt_km

__bt_hook() {
    [[ -n $__bt_w ]] && printf 'l\0%s\0%s\0' "$READLINE_LINE" "$READLINE_POINT" >&"$__bt_w"
}
__bt_ehook() {
    [[ -n $__bt_w ]] && printf 'e\0%s\0%s\0' "$READLINE_LINE" "$READLINE_POINT" >&"$__bt_w"
}
__bt_accept() {
    [[ -n $__bt_w ]] && printf 'a\0' >&"$__bt_w"
}
__bt_tab() { __bt_menu t; }
__bt_stab() { __bt_menu T; }
__bt_menu() {
    if [[ -z $__bt_w ]]; then
        return 0
    fi
    local reply
    __bt_busy=1
    printf '%s\0%s\0%s\0' "$1" "$READLINE_LINE" "$READLINE_POINT" >&"$__bt_w"
    while IFS= read -r -d '' -u "$__bt_r" -t 5 reply; do
        case $reply in
        I)
            IFS= read -r -d '' -u "$__bt_r" -t 5 READLINE_LINE
            IFS= read -r -d '' -u "$__bt_r" -t 5 READLINE_POINT
            break
            ;;
        C)  # the daemon wants the compspec of a command
            IFS= read -r -d '' -u "$__bt_r" -t 5 reply
            { printf 'S\0'; complete -p -- "$reply" 2>/dev/null || complete -p -D 2>/dev/null; printf '\0'; } >&"$__bt_w"
            ;;
        R) __bt_compspec ;;
        *) break ;;
        esac
    done
    __bt_busy=
    printf 'd\0' >&"$__bt_w"
}

# Run one part of a compspec on behalf of the daemon (bash's programmable
# completion machinery only runs from readline's own Tab). Results are
# streamed back as newline-separated lines.
__bt_compspec() {
    local kind arg cmd n i w st=0
    local COMP_LINE COMP_POINT COMP_CWORD COMP_TYPE=9 COMP_KEY=9 COMPREPLY=() __bt_compopts=
    local -a COMP_WORDS=()
    IFS= read -r -d '' -u "$__bt_r" -t 5 kind
    IFS= read -r -d '' -u "$__bt_r" -t 5 arg
    IFS= read -r -d '' -u "$__bt_r" -t 5 cmd
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_CWORD
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_LINE
    IFS= read -r -d '' -u "$__bt_r" -t 5 COMP_POINT
    IFS= read -r -d '' -u "$__bt_r" -t 5 n
    for ((i = 0; i < n; i++)); do
        IFS= read -r -d '' -u "$__bt_r" -t 5 w
        COMP_WORDS+=("$w")
    done
    local cur=${COMP_WORDS[COMP_CWORD]-} prev=
    (( COMP_CWORD > 0 )) && prev=${COMP_WORDS[COMP_CWORD-1]}
    case $kind in
    F)
        # `compopt` only works inside readline's completion; shim it so that
        # completion functions can still tell us about nospace/filenames.
        compopt() {
            local o
            while (( $# )); do
                case $1 in
                -o) __bt_compopts+=" $2"; shift ;;
                +o) __bt_compopts=${__bt_compopts// $2/}; shift ;;
                esac
                shift
            done
            return 0
        }
        "$arg" "$cmd" "$cur" "$prev" 2>/dev/null
        st=$?
        unset -f compopt
        { printf 'Q\0%s\0%s\0' "$st" "$__bt_compopts"; (( ${#COMPREPLY[@]} )) && printf '%s\n' "${COMPREPLY[@]}"; printf '\0'; } >&"$__bt_w"
        ;;
    W) { printf 'Q\0%s\0%s\0' 0 ''; compgen -W "$arg" -- "$cur" 2>/dev/null; printf '\0'; } >&"$__bt_w" ;;
    A) { printf 'Q\0%s\0%s\0' 0 ''; compgen -A "$arg" -- "$cur" 2>/dev/null; printf '\0'; } >&"$__bt_w" ;;
    G) { printf 'Q\0%s\0%s\0' 0 ''; compgen -G "$arg" 2>/dev/null; printf '\0'; } >&"$__bt_w" ;;
    C) { printf 'Q\0%s\0%s\0' 0 ''; eval "$arg" '"$cmd" "$cur" "$prev"' 2>/dev/null; printf '\0'; } >&"$__bt_w" ;;
    *) printf 'Q\0%s\0%s\0\0' 1 '' >&"$__bt_w" ;;
    esac
    return 0
}

# The daemon sends SIGWINCH when it has something to paint. Readline handles
# the signal (redrawing the line) before this trap runs, so what we paint on
# top of it stays.
__bt_winch() {
    if [[ -n $__bt_busy ]]; then
        printf 'r\0' >&"$__bt_w"
    elif [[ -n $__bt_w ]]; then
        printf 'g\0' >&"$__bt_w"
        if read -r -N 1 -u "$__bt_r" -t 2 __bt_ack && [[ $__bt_ack == y ]]; then
            __bt_below=1
        else
            __bt_below=
        fi
    fi
    if [[ -n $__bt_user_winch ]]; then
        eval "$__bt_user_winch"
    fi
}

# Erase the completion list before a command's output starts. Runs from the
# DEBUG trap, so it must ignore our own hooks and always return 0 (with
# `extdebug`, a non-zero status would skip the command).
__bt_preexec() {
    if [[ -n $__bt_below && $BASH_COMMAND != __bt_* && ${FUNCNAME[1]-} != __bt_* ]]; then
        printf '\e[J' >&2
        __bt_below=
    fi
    return 0
}

__bt_connect() {
    local path pid
    read -r -u "$__bt_r" -t 5 path pid || return 1
    exec {__bt_w}<>"$path" || return 1
    __bt_pid=$pid
    printf 'i\0%s\0%s\0%s\0%s\0%s\0%s\0' "$$" "$HOME" "${HISTFILE-}" "${BASH_TOOLS_STYLES-}" \
        "$__bt_rows" "${BASH_TOOLS_OPTS-}" >&"$__bt_w"
    { printf 'V\0'; bind -v; printf '\0'; } >&"$__bt_w"
    __bt_refresh
    return 0
}
__bt_refresh() {
    { printf 'A\0'; compgen -A alias; printf '\0F\0'; compgen -A function; printf '\0'; } >&"$__bt_w"
}
__bt_disable() {
    [[ -n $__bt_w ]] && printf 'x\0' >&"$__bt_w"
    __bt_w=
    bind '"\C-i": complete'
    bind '"\e[Z": menu-complete-backward'
}

__bt_prompt() {
    if [[ -z $__bt_w ]]; then
        __bt_connect || return 0
    elif ! kill -0 "$__bt_pid" 2>/dev/null; then
        __bt_disable
        return 0
    fi
    local ps1=${PS1@P} ps2=${PS2@P} nl n
    nl=${ps1//[!$'\n']/}
    n=$(( __bt_rows + ${#nl} ))
    if (( n > 0 )); then
        printf '\e[J%s%s\e[%dA' "$__bt_nl" "$nl" "$n" >&2
    else
        printf '\e[J' >&2
    fi
    printf 'p\0%s\0%s\0%s\0%s\0%s\0' "$ps1" "$ps2" "$PWD" "$PATH" "$n" >&"$__bt_w"
    if (( HISTCMD > 1 )); then
        { printf 'H\0'; fc -ln -1 2>/dev/null; printf '\0'; } >&"$__bt_w"
    fi
    if (( EPOCHSECONDS - __bt_last_refresh >= 5 )); then
        __bt_last_refresh=$EPOCHSECONDS
        __bt_refresh
    fi
    return 0
}

# Hook into PROMPT_COMMAND (string or array), the DEBUG trap (or bash-preexec
# when it is loaded) and the WINCH trap (chaining an existing one).
if [[ ${PROMPT_COMMAND@a} == *a* ]]; then
    PROMPT_COMMAND+=(__bt_prompt)
else
    PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}__bt_prompt"
fi
if [[ -n ${preexec_functions+x} ]] || declare -F __bp_install >/dev/null 2>&1; then
    preexec_functions+=(__bt_preexec)
else
    if (( BASH_VERSINFO[0] > 5 || BASH_VERSINFO[1] >= 3 )); then
        eval '__bt_t=${ trap -p WINCH DEBUG; }'
    else
        __bt_t=$(trap -p WINCH DEBUG)
    fi
    __bt_old_debug=
    while IFS= read -r __bt_line; do
        case $__bt_line in
        "trap -- "*" SIGWINCH")
            __bt_line=${__bt_line#trap -- }
            eval "__bt_user_winch=${__bt_line% SIGWINCH}"
            ;;
        "trap -- "*" DEBUG")
            __bt_line=${__bt_line#trap -- }
            eval "__bt_old_debug=${__bt_line% DEBUG}"
            ;;
        esac
    done <<< "$__bt_t"
    if [[ -n $__bt_old_debug ]]; then
        trap "__bt_preexec; $__bt_old_debug" DEBUG
    else
        trap '__bt_preexec' DEBUG
    fi
    unset __bt_t __bt_line __bt_old_debug
fi
trap '__bt_winch' WINCH
